services:
  rstudio:
    build:
      context: .
      args:
        R_VERSION: "4.5"
    ports:
      - "8787:8787"
    environment:
      PASSWORD: "r-dev"
    volumes:
      - .:/home/rstudio/project
      - renv-library:/home/rstudio/project/renv/library
      - renv-cache:/home/rstudio/.cache/R/renv

volumes:
  renv-library:
  renv-cache:
